# Generated by Django 2.2 on 2019-04-05 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Enter groupname:', verbose_name='Name')),
                ('description', models.TextField(blank=True, help_text='Enter groupname', null=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Enter username: ', max_length=100, verbose_name='Nickname')),
                ('created', models.DateField(auto_now_add=True, help_text='Enter date:', verbose_name='Date of created')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='task.Group', verbose_name='Group')),
            ],
        ),
    ]
