# Generated by Django 2.2 on 2019-04-06 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20190405_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(blank=True, help_text='Enter description: ', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created',
            field=models.DateField(auto_now_add=True, help_text='Enter date: ', verbose_name='Date of created'),
        ),
    ]
