# Generated by Django 2.2 on 2019-04-06 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_auto_20190406_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='create',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='group',
            name='delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='group',
            name='edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='', error_messages={'invalid': 'example@mail.com'}, max_length=254, unique=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Enter username: ', max_length=100, unique=True, verbose_name='Nickname'),
        ),
    ]
