# Generated by Django 2.2 on 2019-04-06 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0011_auto_20190406_1810'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaginatorElements',
        ),
        migrations.RemoveField(
            model_name='group',
            name='create',
        ),
        migrations.RemoveField(
            model_name='group',
            name='delete',
        ),
        migrations.RemoveField(
            model_name='group',
            name='edit',
        ),
    ]
