# Generated by Django 2.2 on 2019-04-06 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0012_auto_20190406_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='create',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='delete',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='edit',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
