# Generated by Django 2.2 on 2019-04-06 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0014_auto_20190406_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='creating',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='group',
            name='deleting',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='group',
            name='editing',
            field=models.BooleanField(default=False),
        ),
    ]
